apiVersion: v1
kind: ReplicationController
metadata:
 name: mynginxpod1
spec:
 replicas: 3
 template:
   metadata:
     labels:
       app: development
   spec:
     containers:
        - image: nginx
          name: nginxcontainer
          ports:
            - containerPort: 80
          
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
